### ISSUE TITLE
static library

### ISSUE THREAD

**Issue by SomeCoderName66** [wbenny/mini-tor#16] opened 2019-02-28 16:49 UTC
Hello, wbenny. I compiled mini-tor as a static lib and had no errors. However when I tried to link it into project I had 188 errors in mini-tor .h and .cpp files. Can you help me please, I can't understand what I am doing wrong.

**Comment by hatter74** [comment] 2019-03-25 05:54
+1 - It would be great to get a short tutorial on how to compile this as a .lib, and how to include and use it in a C++ program. That would be a huge value add

**Comment by wbenny** [comment] 2019-03-31 12:06
Duplicate of #14

**Closed by wbenny** 2019-03-31 12:06 UTC

**Comment by hatter74** [comment] 2019-04-09 16:19
This is what happens when a coder is both smart, and unhelpful. We like his product, and want to use it in a different way... but, eff me, right?? Cmon wbenny, don't be like that.. We're asking for help setting up a core use-case for your software, and you don't want to lift a finger. How about this - if you put up a BTC donation page, I'll even pay you to put together a tutorial for us.

**Comment by wbenny** [comment] 2019-04-09 16:53
mini-tor isn't product, it is merely PoC for anyone who is interested in how TOR protocol works. Anyone who wants to incorporate TOR into their product should use original TOR.

Anyway, in [lib branch](https://github.com/wbenny/mini-tor/tree/lib) I've separated the code into static library (according to the steps I've mentioned above), so you can use it as a starting point. Maybe in a future I'll merge this change into `master` branch, as I'm usually making my C++ projects as static libraries - and this one has been exception.

For anyone who is considering donation, there is `BTC`/`LTC` address at the bottom of the README.md.
